package types

const NSEVENT_TRUSTED = 1000000

const NSEVENT_CONNECTED = 100
const NSEVENT_ACCEPTED = -50
const NSEVENT_DISCONNECTED = -43
const NSEVENT_CONNECTING = -13

const NSEVENT_PUSH_BLOCK = 20
const NSEVENT_PUSH_TX = 10

const NSEVENT_INTERNAL_ERROR = -100
const NSEVENT_REQUEST_TIMEOUT = -5
const NSEVENT_BLOCK_ERROR = -500
const NSEVENT_TX_ERROR = -500
const NSEVENT_TX_NODATA = -50
